version: '3'
services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./Frontend/app
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run serve"
    volumes:
      - ./Frontend/app:/usr/src/app
volumes:
  myapp:
    external: true
